
import React from 'react';

export const MetaData = ({ title, description }) => {
  return (
    <>
      <title>Admin</title>
      <meta name="description" content={"Generated by BeyzaArıbaş"} />
     
    </>
  );
};
